# Favicon
favicon:

# SEO
keywords:

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# Nav menu
menu:
  Home: /
  #  Summary: /summary
  Categories: /categories
  Archives: /archives
  About: /about
  RSS: /atom.xml
