name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: hexo
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
          GITMENT_CLIENT_ID: ${{ secrets.GITMENT_CLIENT_ID }}
          GITMENT_CLIENT_SECRET: ${{ secrets.GITMENT_CLIENT_SECRET }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          sed -i "s/gh_gitment_cid/${GITMENT_CLIENT_ID}/g" ./_config.yml
          sed -i "s/gh_gitment_csecret/${GITMENT_CLIENT_SECRET}/g" ./_config.yml
          git config --global user.email "daibingzhi9519@outlook.com"
          git config --global user.name "Tiehichi"
          npm install hexo-cli -g
          npm install
          npm install hexo-deployer-git --save
      - name: Hexo deploy
        run: |
          hexo clean
          hexo d